import '@styles/globals.css'
import { Quicksand } from 'next/font/google'

import { Navbar } from '@components/navbar'

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} bg-slate-50`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
